apiVersion: skaffold/v2alpha3
#apiVersion: skaffold/v4beta2
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local: 
    push: false
  #googleCloudBuild:
  #  projectId: project-ticketing-dev
  artifacts:
    - image: cristiancasd/ticketing-auth
  #  - image: us.gcr.io/project-ticketing-dev/ticketing-auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: cristiancasd/ticketing-client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: cristiancasd/ticketing-tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
